Updated rse calculator with tests
waterloo-rocketry/RSE-calculator pull request #2
Opened 2021-02-02 02:07 UTC by Code-Titan

Updated RSE calculator

- Fully tested with a test suite for all core calculator functions
- Selection of sample output files for testing
- constants now stored in yaml
- folders for organization
- data input and storage using .csv files

2021-02-05 21:11 UTC, jacobdeery reviewed
First pass review is done. The first few files are pretty comprehensively commented; the rest are more sparsely commented, but most of the comments from the first files still carry over (especially regarding numpy arrays). I didn't review the unit tests, since they'll need to change anyways after we change the corresponding functions.

There are also a lot of minor formatting issues. Rather than trying to fix them manually, I suggest copying over the `format.sh` script that we use in Topside.

> Reviewed 33 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MSo0awR1EhJjg1wy7g0:b3xspl0)* status: 33 of 42 files reviewed, 44 unresolved discussions (waiting on @Code-Titan, @shillcoat, @usephysics, and @wendi-yu)

___
*[calculator_main.py, line 10 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnme9W-xsraeZPU0Io:-MSnme9W-xsraeZPU0Ip:b-kjham4) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L10)):*
> ```
> constants_file_path = None
> ```
It doesn't look like this parameter is used for anything
___
*[calculator_main.py, line 25 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnmlHwBnSEYy2vnWtZ:-MSnmlHwBnSEYy2vnWt_:bfnmtir) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L25)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     file = open(target_path, 'w')
>     for tag in engine_XML.XML_tags:
>         file.write(tag)
>         file.write('\n')
>     file.close()
> ```
</details>

prefer using `with open(target_path, 'w') as file` instead so that you don't need to explicitly close the file
___
*[calculator_main.py, line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnmY9XC6ySOyU9UVkI:-MSnmY9XC6ySOyU9UVkJ:b-fcefpf) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L26)):*
> ```
> supress
> ```
suppress
___
*[calculator_main.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnm_2VE0B7hhcWLapd:-MSnm_2VE0B7hhcWLape:b-vzl79y) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L27)):*
> ```
> sucessful
> ```
successful
___
*[constants.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnnCxp32xcnv-Cbe90:-MSnnCxp32xcnv-Cbe91:b-nar0aa) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L108)):*
> ```
> diameter = (None, 2.5, 3, 3.625, 3, 2.5)
> ```
I would suggest making this a numpy array and dropping the `None` at the beginning: `diameter = np.array([2.5, 3, 3.625, 3, 2.5])`. This makes everything else much simpler (the radius calculation, for example, just becomes `radius = diameter_to_radius(diameter)`.
___
*[constants.py, line 169 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnnk1T5nRjM9P_Y3oa:-MSnnk1T5nRjM9P_Y3ob:b-w04jxh) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L169)):*
> ```
> None
> ```
Why have `None` at the beginning?
___
*[constants.py, line 196 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnolQU3BWM2mpeusFQ:-MSnokXg2yOgXSRZyviH:bxjsxix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L196)):*
> ```
> ConstantsManager
> ```
This class seems to hold the same data as all of the above classes, but doesn't interact with them at all. What is the purpose of this duplication?
___
*[constants.py, line 202 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSno1NqDtPtw6uYRkrl:-MSno1Nr74RW7i8E4d8g:biy3f18) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L202)):*
> ```
> path = None
> ```
you can just use `path=self.DEFAULT_PATH`
___
*[csv_extractor.py, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnoviv8MjsrOTI4Qvl:-MSnoviv8MjsrOTI4Qvm:b-4j5akx) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/csv_extractor.py#L4)):*
> ```
> ()
> ```
No parens needed
___
*[csv_extractor.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpUO6CrOciHPrjTD1:-MSnpUO6CrOciHPrjTD2:b-7u5fr1) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/csv_extractor.py#L108)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         if new_file_path is None:
>             split_path = target_file_path.split('\\')
>             split_path[-1] = 'downsampled_' + split_path[-1]
>             new_file_path = '\\'.join(split_path)
>             print('new file path: ' + new_file_path)
> ```
</details>

Use [os.path](https://docs.python.org/3/library/os.path.html) instead of manual string manipulation.
___
*[DAQ_pressure_to_density.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpfsAEyxqRP7Kkf9d:-MSnpfsAEyxqRP7Kkf9e:b-cxgkdk) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L29)):*
> ```
> insdex
> ```
index
___
*[DAQ_pressure_to_density.py, line 32 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnphTp96cyABlhmWxZ:-MSnphTp96cyABlhmWx_:b2y6e1h) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L32)):*
> ```
>  and False
> ```
What is this for?
___
*[DAQ_pressure_to_density.py, line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnq6757r5y1wh_h7G8:-MSnq6757r5y1wh_h7G9:b1385cc) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L50)):*
> ```
> Stores results in self.t_reduced.
> ```
This doesn't seem to be the case
___
*[DAQ_pressure_to_density.py, line 79 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpn4f1MxwLvwk6qMd:-MSnpn4f1MxwLvwk6qMe:b-cg3xp3) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L79)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #             print(DAQ_data.tank_pressure_psia[i])
> #             print(closest_p[i])
> #             print(next_p[i])
> #             print(temp_at_closest_p[i])
> #             print('next')
> ```
</details>

Remove
___
*[DAQ_pressure_to_density.py, line 82 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnqMEUBP84dMqJ0gB2:-MSnqMEV6QECLKx9UnLX:b-i6he8c) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L82)):*
> ```
>             try:
>                 frac = (DAQ_data.tank_pressure_psia[i] - closest_p[i])/(next_p[i] - closest_p[i])
>                 result = (frac + temp_at_closest_p[i])/critical_temp
> ```
Since we're using Python, we can just use [NumPy interpolate](https://numpy.org/doc/stable/reference/generated/numpy.interp.html) instead of re-implementing this ourselves. This lets us get rid of the whole `closest_p/next_p` calculation entirely.
___
*[DAQ_pressure_to_density.py, line 172 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnquFMBgNw69jNz7LA:-MSnquFMBgNw69jNz7LB:b-rigdvz) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d0 [...]

2021-02-05 23:18 UTC, shillcoat requested changes
I took a quick look, in addition to using NumPy as Jacob suggested (I think that will help simplify a lot of your code) I'm concerned about the management of constants. The constants read in from the YAML file don't appear to be used and instead each function uses its own hard-coded value, which is bad for readability and will also make updating the code to reflect different engine parameters more difficult.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MSoTSUaEooFHO_qmE9h:b-ycxb2m)* status: 33 of 42 files reviewed, 45 unresolved discussions (waiting on @Code-Titan, @usephysics, and @wendi-yu)

___
*[constants.py, line 196 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSoQndcDVYQHtw4RxeW:-MSoQndcDVYQHtw4RxeX:b-gzcs3o) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L196)):*
> ```Python
>     water_used_for_heating = 15      #pounds (lb)
> 
> class ConstantsManager:
> ```

If we have a system for reading in and managing constants, why are they still hard-coded throughout the code as well? All other places in the code should refer back to the ConstantsManager object for these values rather than using their own defined versions of them.


<!-- Sent from Reviewable.io -->

2021-02-07 06:41 UTC, Code-Titan reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: 21 of 43 files reviewed, 45 unresolved discussions (waiting on @Code-Titan, @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[calculator_main.py, line 10 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnme9W-xsraeZPU0Io:-MStEU-bCmdP8gnxM62s:b35wahc) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L10)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> constants_file_path = None
> ```
It doesn't look like this parameter is used for anything
</blockquote></details>

The intention was to implement the ability to pass in a constants file source for individual calculation executions. I have worked that in properly now.  
___
*[calculator_main.py, line 25 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnmlHwBnSEYy2vnWtZ:-MStEyud7ypPUXLkWvhB:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L25)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     file = open(target_path, 'w')
>     for tag in engine_XML.XML_tags:
>         file.write(tag)
>         file.write('\n')
>     file.close()
> ```
prefer using `with open(target_path, 'w') as file` instead so that you don't need to explicitly close the file
</blockquote></details>

Done.
___
*[calculator_main.py, line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnmY9XC6ySOyU9UVkI:-MStF47rBb_-D1KdTTgX:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L26)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> supress
> ```
suppress
</blockquote></details>

Done.
___
*[calculator_main.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnm_2VE0B7hhcWLapd:-MStF5mF21-kblKVVEn4:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/calculator_main.py#L27)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> sucessful
> ```
successful
</blockquote></details>

Done.
___
*[constants.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnnCxp32xcnv-Cbe90:-MSuykCN3w_tYyjCkzeK:b-wh0kgf) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L108)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> diameter = (None, 2.5, 3, 3.625, 3, 2.5)
> ```
I would suggest making this a numpy array and dropping the `None` at the beginning: `diameter = np.array([2.5, 3, 3.625, 3, 2.5])`. This makes everything else much simpler (the radius calculation, for example, just becomes `radius = diameter_to_radius(diameter)`.
</blockquote></details>

This class is being phased out. I'm not sure if this ought to be implemented in `ConstantsManager`, but even there all the calculations occur once so I'm not sure if there is a lot of value in converting them to numpy arrays.
___
*[constants.py, line 169 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnnk1T5nRjM9P_Y3oa:-MStFO5d9J8is1HC6mCy:b-hggia) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L169)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> None
> ```
Why have `None` at the beginning?
</blockquote></details>

This is to make the indexing closer to the original documentation, where all list counts began with 1.
___
*[constants.py, line 196 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnolQU3BWM2mpeusFQ:-MStF_8xD-totGbi4LG8:bcl0c49) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L196)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ConstantsManager
> ```
This class seems to hold the same data as all of the above classes, but doesn't interact with them at all. What is the purpose of this duplication?
</blockquote></details>

Duplication was unnecessary, I had intended to move all functionality to the ConstantsManager. It looks like there were still some references to the hard-coded values, but I have now removed all of those and the hard-coded values themselves.
___
*[constants.py, line 196 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSoQndcDVYQHtw4RxeW:-MStFyOb0qtVYH5pA2a_:b9nf571) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L196)):*
<details><summary><i>Previously, shillcoat (Sophie) wrote…</i></summary><blockquote>

If we have a system for reading in and managing constants, why are they still hard-coded throughout the code as well? All other places in the code should refer back to the ConstantsManager object for these values rather than using their own defined versions of them.
</blockquote></details>

Done, all places now use the manager.
___
*[constants.py, line 202 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSno1NqDtPtw6uYRkrl:-MStGFR4CoKDLHQ-mW27:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L202)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> path = None
> ```
you can just use `path=self.DEFAULT_PATH`
</blockquote></details>

Done.
___
*[csv_extractor.py, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnoviv8MjsrOTI4Qvl:-MStG_SpAOgHBjLDRaFE:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/csv_extractor.py#L4)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ()
> ```
No parens needed
</blockquote></details>

Done.
___
*[csv_extractor.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpUO6CrOciHPrjTD1:-MStH8fI5ab6qnVQ2xs9:bmynzsv) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/csv_extractor.py#L108)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         if new_file_path is None:
>             split_path = target_file_path.split('\\')
>             split_path[-1] = 'downsampled_' + split_path[-1]
>             new_file_path = '\\'.join(split_path)
>             print('new file path: ' + new_file_path)
> ```
Use [os.path](https://docs.python.org/3/library/os.path.html) instead of manual string manipulation.
</blockquote></details>

I'm not sure exactly what would be best here. Did you have in mind using os.path.split() and os.path.join() ? If yes, I can add that in.
___
*[DAQ_pressure_to_density.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpfsAEyxqRP7Kkf9d:-MStHx4_6XWwx2OkZwv3:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L29)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> insdex
> ```
index
</blockquote></details>

Done.
___
*[DAQ_pressure_to_density.py, line 32 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnphTp96cyABlhmWxZ:-MStIJ6U4qve6ezdbXQ8:bn45lud) ([raw file](https://github.com/ [...]

2021-02-08 07:30 UTC, Code-Titan reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: 21 of 43 files reviewed, 45 unresolved discussions (waiting on @Code-Titan, @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[DAQ_pressure_to_density.py, line 82 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnqMEUBP84dMqJ0gB2:-MT-Q4EE6pUthkGDFvg4:bl29g76) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L82)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I'm not exactly sure how to implement this well. One way that I could do it is to cut out all of the closest P and next P stuff, then simply execute`t_reduced = (interp(DAQ_data.tank_pressure_psia, self.vapour_pressure_data.pressure_psi, self.vapour_pressure_data.t_kelvin))/self.consts_m.nitrous_oxide_properties['critical_temp']` to get the reduced temperatures, which seems to work. However, I feel that some flexibility may be sacrificed by doing it this way. 
</blockquote></details>

After looking into it, I figured that there wouldn't be any real downsides. This has been implemented. 
___
*[DAQ_pressure_to_density.py, line 198 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnr56qA6_LXdPtLqoF:-MT-Dk9X4GKmS1gkWmoR:b-6pxz9q) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_pressure_to_density.py#L198)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         self.one_minus_t_reduced = [1 - x for x in self.t_reduced]
>         self.reciprocal_t_reduced_minus_one = [(1 / x) - 1 for x in self.t_reduced]
> ```
I would really suggest making these numpy arrays rather than using list comprehensions. The code will be much easier to read. These two lines, for example, simply become:

```
self.one_minus_t_reduced = 1 - self.t_reduced
self.reciprocal_t_reduced_minus_one = 1/self.t_reduced - 1
```
</blockquote></details>

All relevant lists are being switched over to numpy. 
___
*[DAQ_raw.py, line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnrfTXEbMwJLmiai4m:-MT-X4VkDmNC3i5RfWDW:b-1umiso) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_raw.py#L43)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> [float(time) for time in i_time_s]
> ```
Use numpy arrays
</blockquote></details>

In the process of changing all lists to numpy arrays. 


<!-- Sent from Reviewable.io -->

2021-02-09 06:07 UTC, Code-Titan reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: 21 of 43 files reviewed, 45 unresolved discussions (waiting on @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[engine_CG.py, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnsC9CB54kHaU4Ms59:-MT-YHjq7RkFCJXvDMOs:b-3idqb1) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/engine_CG.py#L33)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I hardcoded it for now such that I could compare output files with the xml from the original excel sheet(where it was also hardcoded). I get the feeling that this value will have to change for every thrust curve passed into the calculator. As such, it might be best to implement it as a constant in the configuration file, or to have the user pass it into the calculation via command line query.  An even more sophisticated way would be to run some sort of falling edge detector that will automatically calculate the end of burn. Thoughts?
</blockquote></details>

I'll be implementing this into the constants file.
___
*[tests/test_DAQ_pressure_to_density.py, line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSo-DSlDOtdS5cQ_OFS:-MT4HPGe84CuO-qikVXJ:b-yzpvuo) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/tests/test_DAQ_pressure_to_density.py#L52)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>     for idx in range(len(test_results)):
>         assert abs(correct_results_approx[idx] - test_results[idx]) < 0.01
> ```
Use [allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)
</blockquote></details>

This specific test is no longer done as it was for interpolation, but I have also optimized some test functions to use allclose in other parts of the code as well.


<!-- Sent from Reviewable.io -->

2021-02-09 06:16 UTC, Code-Titan commented
___
*[csv_extractor.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpUO6CrOciHPrjTD1:-MT4Qgm6DIxKiDKWeY3g:beyczlh) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/csv_extractor.py#L108)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I'm not sure exactly what would be best here. Did you have in mind using os.path.split() and os.path.join() ? If yes, I can add that in.
</blockquote></details>

Added that in.


<!-- Sent from Reviewable.io -->

2021-02-13 03:51 UTC, jacobdeery reviewed
Ok, looks much better! There are still a few places where we can clean things up a bit, but I think we're almost there.

> Reviewed 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MTOVtsKAo2-FCbGI_L6:b9eqy3k)* status: all files reviewed, 23 unresolved discussions (waiting on @Code-Titan, @shillcoat, @usephysics, and @wendi-yu)

___
*[constants.py, line 169 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnnk1T5nRjM9P_Y3oa:-MTONL6q-eSRsXRasjdk:b-if3vsp) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L169)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

This is to make the indexing closer to the original documentation, where all list counts began with 1.
</blockquote></details>

I don't think that's necessary - let's focus on making this code as good as possible rather than tying it to Excel's limitations.
___
*[constants.py, line 170 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTONX9nCu9C96skLUDa:-MTONX9nCu9C96skLUDb:bu0dl9e) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L170)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         radius = (None, diameter_to_radius(diameter[1]),
> 
>                   diameter_to_radius(diameter[2]),
> 
>                   diameter_to_radius(
> 
>                       diameter[3]), diameter_to_radius(diameter[4]),
> 
>                   diameter_to_radius(diameter[5]))
> ```
</details>

Prefer using numpy arrays here for readability
___
*[csv_extractor.py, line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnpUO6CrOciHPrjTD1:-MTONfkYEZwUZBBnGB1F:bff5zk8) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/csv_extractor.py#L108)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

Added that in.
</blockquote></details>

This looks good.
___
*[DAQ_pressure_to_density.py, line 102 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTONuyIDvH8bKYbw1CX:-MTONuyIDvH8bKYbw1CY:b-dbzyv2) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/DAQ_pressure_to_density.py#L102)):*
> ```
> np.array
> ```
I don't think you need to manually declare this; doesn't `np.interp` already return a `np.array`?
___
*[DAQ_raw.py, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnrkXc9C8yiO2MwCz9:-MTOOLwzCXFdlZakXB5O:br7fi4o) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/DAQ_raw.py#L17)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

It's a personal style thing: for initialization parameters being passed in that are intended to be copied inside the class, I prefix `i_` to mean 'input' or 'initialization'. I can remove it if needed.
</blockquote></details>

I was just curious. If it's more clear for you, feel free to leave it.
___
*[DAQ_raw.py, line 44 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOOIcl4PCixii-euzK:-MTOOIcl4PCixii-euzL:b-vjdszz) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/DAQ_raw.py#L44)):*
> ```
> n_array([float(time) for time in i_time_s])
> ```
you should be able to just make this `n_array(i_time_s)` (same with the other lists here)
___
*[engine_CG.py, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnsC9CB54kHaU4Ms59:-MTOOioO1ejjw6n6rLo9:b-hi25ql) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/engine_CG.py#L33)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I'll be implementing this into the constants file.
</blockquote></details>

Constants file is fine. Automatic calculation of the end of burn (e.g. by thresholding on thrust) will be nice to add later but not necessary for now.
___
*[engine_CG.py, line 124 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnsz492sJgCsHEnvav:-MTOPHXU4yu4dOmtI1nY:btayuzg) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/engine_CG.py#L124)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

If a full data object is passed in I want that to be used instead of the other parameters. 
</blockquote></details>

Ok. This part is fine.
___
*[engine_CG.py, line 93 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOOyoC022go7dXZaPw:-MTOOyoC022go7dXZaPx:b1zmqhq) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L93)):*
> ```Python
> #         self.propellant_CG_in = [(self.DAQ_data.adjusted_mass_lb[idx]*(self.NOS_CG_in[idx] + y_OS)
> #                                   + self.fuel_mass_lb[idx]*fuel_CG)/self.propellant_mass_lb[idx]
> #                                  for idx in range(len(self.DAQ_data.time_s))]
> ```

Remove commented code here and above
___
*[engine_CG.py, line 146 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOTKwRAi-H_j5DEjOu:-MTOTKwS-n1DnhEjM2Lt:b-63crub) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L146)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>         if not hasattr(liquid_mass, '__iter__'):
>             liquid_mass = [liquid_mass]
>         if not hasattr(vapour_mass, '__iter__'):
>             vapour_mass = [vapour_mass]
>         if not hasattr(liquid_cg_in, '__iter__'):
>             liquid_cg_in = [liquid_cg_in]
>         if not hasattr(vapour_cg_in, '__iter__'):
>             vapour_cg_in = [vapour_cg_in]
> ```
</details>

You shouldn't need any of this or the `for` loop below since we're using numpy arrays instead of lists. You should be able to just use

```
result = (liquid_mass[val_idx]*liquid_cg_in[val_idx] + vapour_mass[val_idx]*vapour_cg_in[val_idx])
result /= (liquid_mass[val_idx] + vapour_mass[val_idx])
```

directly, and it will work for both floats and numpy arrays.
___
*[engine_CG.py, line 184 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOU--Z5XWy6u_FY_u1:-MTOU--Z5XWy6u_FY_u2:b-vcrvs) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L184)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         for time_stamp in time:
>             result = m_FI - ((m_FI-m_FF)/(time[end_of_burn] - time[0])) *\
>                 (time_stamp - time[0])
>             values.append(result)
> ```
</details>

No need for the `for` loop since `time` will be a numpy array. You can just use:

```
result = m_FI - ((m_FI-m_FF)/(time[end_of_burn] - time[0])) * (time_stamp - time[0])
```
___
*[main.py, line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnuR5ZBcMxToWL96gF:-MTOVsLP4sk-H15tj6rh:b-8dahjt) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/main.py#L6)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

Looks like no, reason, I'm removing it.
</blockquote></details>

Still there
___
*[NOS_liquid_CG.py, line 143 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOPh05-jb-zzocx5O8:-MTOPh05-jb-zzocx5O9:byp18fd) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/NOS_liquid_CG.py#L143)):*
> ```Python
>                     [...]

2021-02-15 23:59 UTC, wendi-yu requested changes
I also looked things over, mostly just best practice comments from me

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MTc7c-L20a2wFgg1fmu:bgy8s19)* status: all files reviewed, 30 unresolved discussions (waiting on @Code-Titan, @jacobdeery, @shillcoat, and @usephysics)

___
*[constants.py, line 9 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTbxPjg8JSvnTPKP0Zo:-MTbxPjh2mzR9b3bsvAw:b-bmtopp) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L9)):*
> ```Python
> def find_volume_cylinder(r, l):
>     '''
>     Returns the volume of a cylinder.
> ```

Iirc docstrings are supposed to be in imperative? I think we should also try and have consistent punctuation for the docstrings. Here's the [pep](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings)
___
*[constants.py, line 160 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTbzRlx0FD7-6Be2nN8:-MTbyBvq8jFLDI2GzqbY:b-nrdos2) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L160)):*
> ```Python
> 
>         dict:
>             A new dict containing the complete data concerning the tank dimensions
> ```

I think it's generally helpful for documentation to specify the form dicts take. Maybe mention the return `dict` is the same as the input `yaml` dict, only with more fields with the data already processed?
___
*[constants.py, line 170 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTONX9nCu9C96skLUDa:-MTbyTBhDC5fct9TeREN:bx42dlx) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L170)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         radius = (None, diameter_to_radius(diameter[1]),
> 
>                   diameter_to_radius(diameter[2]),
> 
>                   diameter_to_radius(
> 
>                       diameter[3]), diameter_to_radius(diameter[4]),
> 
>                   diameter_to_radius(diameter[5]))
> ```
Prefer using numpy arrays here for readability
</blockquote></details>

It might also be easier to read to use a `map` function or something along those lines to convert to radius. [Here's](https://www.kite.com/python/answers/how-to-map-over-a-numpy-array-in-python) how to do it with numpy arrays. It's also probably more robust to do it iteratively, especially if the length of the array we need to process changes. Same goes for `volumes` below
___
*[csv_extractor.py, line 39 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc-HXiE0Unwu10plnd:-MTc-HXiE0Unwu10plne:b-ukq06z) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/csv_extractor.py#L39)):*
> ```Python
>             how much the output needs to be downsampled by. Default value is 1 (no downsampling).
>         '''
>         csvfile = open(file_path, newline='')
> ```

Do you ever `close` the file? Python will eventually do it automatically if you don't but it's good practice to do it yourself, I think. Or you can do the `with file as open(path)"` thing, which will close the file automatically once the indented block ends.
___
*[csv_extractor.py, line 52 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc-tQu8cjkt9G36ZjW:-MTc-tQv98kwOxgIV4Mi:ba0n3r0) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/csv_extractor.py#L52)):*
> ```Python
> 
>         for idx, itm in enumerate(label_table):
>             if itm == 'Time (s)':
> ```

I think for the sake of robustness, you should call `strip()` and `upper()` on the item and maybe use something like `if desired_string is in itm` instead. That'll make it case and whitespace insensitive, and if you check for contain instead of equals you can leave out the units as well.
___
*[csv_extractor.py, line 114 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc1lzG1MD9P581H-f5:-MTc1lzG1MD9P581H-f6:b-jbsxyd) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/csv_extractor.py#L114)):*
> ```Python
>             print('new file path: ' + new_file_path)
> 
>         reader = open(target_file_path, 'r')
> ```

close reader too?
___
*[engine_CG.py, line 148 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc4MpxBSNTLjd-4284:-MTc4MpxBSNTLjd-4285:b-its4fc) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L148)):*
> ```Python
>             vapour_cg_in = [vapour_cg_in]
> 
>         for val_idx in range(len(liquid_mass)):
> ```

You can use `enumerate` to make this kind of iteration where you need both the value and index easier, looks like this:
```Python
for idx, val in enumerate(liquid_mass):
```
___
*[vapour_pressure_calculations.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc6LBc-4Zgz0u76gx-:-MTc6LBc-4Zgz0u76gx0:bacxvxz) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/vapour_pressure_calculations.py#L15)):*
> ```Python
>     def eqn4_1(curr_t_reduced, curr_one_minus_t_reduced, consts_m):
>         '''
>         Static method mplementation of Equation 4.1 to solve for pressure in kPa
> ```

implementation


<!-- Sent from Reviewable.io -->

2021-02-16 06:01 UTC, Code-Titan reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: all files reviewed, 29 unresolved discussions (waiting on @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[constants.py, line 169 at r1](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MSnnk1T5nRjM9P_Y3oa:-MTatxlS84va7438sMX4:bskfugu) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/074d06c2017e7228d0ba68c7d29f4f422d0d94a9/constants.py#L169)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I don't think that's necessary - let's focus on making this code as good as possible rather than tying it to Excel's limitations.
</blockquote></details>

alright, I've removed this convention from the measurements as well as the equation constants.
___
*[constants.py, line 9 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTbxPjg8JSvnTPKP0Zo:-MTcRuT43P31iloh8g0N:blepqet) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L9)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Iirc docstrings are supposed to be in imperative? I think we should also try and have consistent punctuation for the docstrings. Here's the [pep](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings)
</blockquote></details>

I've done a pass over the comments to standardize them.
___
*[constants.py, line 160 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTbzRlx0FD7-6Be2nN8:-MTcSHnk0ImrLGGHJ84u:b-m5e7h6) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L160)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think it's generally helpful for documentation to specify the form dicts take. Maybe mention the return `dict` is the same as the input `yaml` dict, only with more fields with the data already processed?
</blockquote></details>

That's a good point. Done.
___
*[constants.py, line 170 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTONX9nCu9C96skLUDa:-MTau8et27klSVH5-Scf:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L170)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         radius = (None, diameter_to_radius(diameter[1]),
> 
>                   diameter_to_radius(diameter[2]),
> 
>                   diameter_to_radius(
> 
>                       diameter[3]), diameter_to_radius(diameter[4]),
> 
>                   diameter_to_radius(diameter[5]))
> ```
Prefer using numpy arrays here for readability
</blockquote></details>

Done.
___
*[csv_extractor.py, line 39 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc-HXiE0Unwu10plnd:-MTcLGNMCFYW4nS_QdkY:b-teh0fw) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/csv_extractor.py#L39)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Do you ever `close` the file? Python will eventually do it automatically if you don't but it's good practice to do it yourself, I think. Or you can do the `with file as open(path)"` thing, which will close the file automatically once the indented block ends.
</blockquote></details>

Right, didn't notice that. Done.
___
*[csv_extractor.py, line 52 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc-tQu8cjkt9G36ZjW:-MTcSYnG43TI_DLVTZXc:b-se171w) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/csv_extractor.py#L52)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think for the sake of robustness, you should call `strip()` and `upper()` on the item and maybe use something like `if desired_string is in itm` instead. That'll make it case and whitespace insensitive, and if you check for contain instead of equals you can leave out the units as well.
</blockquote></details>

Sure, I'll put this in.  
___
*[DAQ_pressure_to_density.py, line 102 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTONuyIDvH8bKYbw1CX:-MTauaty1zSZjMlu612t:b-xd3vm6) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/DAQ_pressure_to_density.py#L102)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> np.array
> ```
I don't think you need to manually declare this; doesn't `np.interp` already return a `np.array`?
</blockquote></details>

You're right.
___
*[DAQ_raw.py, line 44 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOOIcl4PCixii-euzK:-MTavI7Z-klbXfia02ia:b-fwtqts) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/DAQ_raw.py#L44)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> n_array([float(time) for time in i_time_s])
> ```
you should be able to just make this `n_array(i_time_s)` (same with the other lists here)
</blockquote></details>

The issue is that the i_time_s is passed in as a string, but I will be changing it to use `ndarry.astype(float)` to make it more numpy-ish.
___
*[engine_CG.py, line 93 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOOyoC022go7dXZaPw:-MTbJOb9Aidj_hSJR0qK:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L93)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Remove commented code here and above
</blockquote></details>

Done.
___
*[engine_CG.py, line 146 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOTKwRAi-H_j5DEjOu:-MTbJ4pbCf5qB7biyvIZ:b-e17y88) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L146)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         if not hasattr(liquid_mass, '__iter__'):
>             liquid_mass = [liquid_mass]
>         if not hasattr(vapour_mass, '__iter__'):
>             vapour_mass = [vapour_mass]
>         if not hasattr(liquid_cg_in, '__iter__'):
>             liquid_cg_in = [liquid_cg_in]
>         if not hasattr(vapour_cg_in, '__iter__'):
>             vapour_cg_in = [vapour_cg_in]
> ```
You shouldn't need any of this or the `for` loop below since we're using numpy arrays instead of lists. You should be able to just use

```
result = (liquid_mass[val_idx]*liquid_cg_in[val_idx] + vapour_mass[val_idx]*vapour_cg_in[val_idx])
result /= (liquid_mass[val_idx] + vapour_mass[val_idx])
```

directly, and it will work for both floats and numpy arrays.
</blockquote></details>

Needed a bit of tweaking, but Done.
___
*[engine_CG.py, line 148 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc4MpxBSNTLjd-4284:-MTcLvBH6D-KhkM6BhZM:bed5679) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L148)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

You can use `enumerate` to make this kind of iteration where you need both the value and index easier, looks like this:
```Python
for idx, val in enumerate(liquid_mass):
```
</blockquote></details>

True, but this code has been removed.
___
*[engine_CG.py, line 184 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOU--Z5XWy6u_FY_u1:-MTbHez86JvVwc8I9xWy:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/09855 [...]

2021-02-18 03:56 UTC, jacobdeery reviewed
Almost there!

> Reviewed 1 of 45 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MTnH6nl65OLQcPRzrw3:b-debr86)* status: 8 of 43 files reviewed, 11 unresolved discussions (waiting on @Code-Titan, @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[constants.py, line 176 at r3](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTnFZGD-fbPMdWpGOI4:-MTnFZGD-fbPMdWpGOI5:b-db4jd3) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/3a45d103e8b980d05c558428785d5f7ab28f6e26/constants.py#L176)):*
> ```
> sum(length[:])
> ```
this can just be `sum(length)`, no need for the index
___
*[DAQ_raw.py, line 44 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOOIcl4PCixii-euzK:-MTnFkee7ZbFwC54rznn:bsrfkwe) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/DAQ_raw.py#L44)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

The issue is that the i_time_s is passed in as a string, but I will be changing it to use `ndarry.astype(float)` to make it more numpy-ish.
</blockquote></details>

Looks good
___
*[DAQ_raw.py, line 76 at r3](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTnFxUb6lLYzJWZvllo:-MTnFxUc6m0ck1aL7LZL:b-dfy1rj) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/3a45d103e8b980d05c558428785d5f7ab28f6e26/DAQ_raw.py#L76)):*
> ```
>         return cls(
>             list(range(data_length)), [100 - 10*x for x in range(data_length)],
>             [1000 - 100*x for x in range(data_length)], [1.0 - 0.1*x for x in range(data_length)])
> ```
I would split this up into two lines:

```
time = np.arange(data_length)
return cls(time, 100 - 10*time, 1000 - 100*time, 1 - 0.1*time)
```

Same comment for function below
___
*[engine_CG.py, line 146 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOTKwRAi-H_j5DEjOu:-MTnGRzV31LInFkSpDz5:bra0mkw) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L146)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

Needed a bit of tweaking, but Done.
</blockquote></details>

The idea is that we don't need these `if` statements at all
___
*[tests/test_vapour_pressure_calculations.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOVUbAE6ty5DeBBza4:-MTnGoyKBtXhMWwlOWYU:bdrzh33) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/tests/test_vapour_pressure_calculations.py#L15)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

OK, allclose is probably better here.
</blockquote></details>

Remove old commented code


<!-- Sent from Reviewable.io -->

2021-02-18 17:21 UTC, Code-Titan reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: 7 of 43 files reviewed, 11 unresolved discussions (waiting on @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[constants.py, line 176 at r3](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTnFZGD-fbPMdWpGOI4:-MTpsdSODdAj7i-_PrmN:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/3a45d103e8b980d05c558428785d5f7ab28f6e26/constants.py#L176)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> sum(length[:])
> ```
this can just be `sum(length)`, no need for the index
</blockquote></details>

Done.
___
*[DAQ_raw.py, line 76 at r3](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTnFxUb6lLYzJWZvllo:-MTptqDw43l-BWwSee3c:bhu36e0) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/3a45d103e8b980d05c558428785d5f7ab28f6e26/DAQ_raw.py#L76)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         return cls(
>             list(range(data_length)), [100 - 10*x for x in range(data_length)],
>             [1000 - 100*x for x in range(data_length)], [1.0 - 0.1*x for x in range(data_length)])
> ```
I would split this up into two lines:

```
time = np.arange(data_length)
return cls(time, 100 - 10*time, 1000 - 100*time, 1 - 0.1*time)
```

Same comment for function below
</blockquote></details>

Very good suggestion. Done.
___
*[engine_CG.py, line 146 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTOTKwRAi-H_j5DEjOu:-MTptFma1WZdzwI4ERSw:bckhg5f) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/engine_CG.py#L146)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

The idea is that we don't need these `if` statements at all
</blockquote></details>

Yeah, the problem that they addressed can now be fixed from the test case side. Done.


<!-- Sent from Reviewable.io -->

2021-02-20 04:18 UTC, wendi-yu reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: 7 of 43 files reviewed, 9 unresolved discussions (waiting on @Code-Titan, @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[constants.py, line 9 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTbxPjg8JSvnTPKP0Zo:-MTxe5YPBQlj6Q6cRhOV:b-n1dccw) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L9)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I've done a pass over the comments to standardize them.
</blockquote></details>

I think a couple of them are still "converts" instead of "convert" or "returns" instead of "return"?
___
*[csv_extractor.py, line 52 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTc-tQu8cjkt9G36ZjW:-MTxashuAHHCdSRLRaV0:b-5mf0kw) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/csv_extractor.py#L52)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

Sure, I'll put this in.  
</blockquote></details>

If you wanted you could leave out the units and check for contains instead (so `if 'TIME' in p_itm:`) , but this looks fine to me too, I doubt the spreadsheet will change much.
___
*[csv_extractor.py, line 126 at r4](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTxbbP7DjAizJe6U0bX:-MTxbbP7DjAizJe6U0bY:b9tjegu) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/fd2e52e1906ca8e2138db3053b6ac312412843f2/csv_extractor.py#L126)):*
> ```Python
> 
>         read_idx = 0
>         for line in reader:
> ```

You can get the index without doing it manually by using `enumerate` - at least I think you can for a reader lol
```Python
for read_idx, line in enumerate(reader):
```
___
*[engine_XML.py, line 88 at r4](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTxcvMs4ljMKsg0SXi7:-MTxcvMs4ljMKsg0SXi8:b-5vgk73) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/fd2e52e1906ca8e2138db3053b6ac312412843f2/engine_XML.py#L88)):*
> ```Python
>             The final propellant CG in mm.
>         '''
>         result = consts_m.tank_dimensions_meters['total_length']*1000
> ```

Nitpick but I think you could just factor out the `*1000` and not multiply it til the end?


<!-- Sent from Reviewable.io -->

2021-02-27 00:45 UTC, Code-Titan reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2)* status: 6 of 43 files reviewed, 7 unresolved discussions (waiting on @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)

___
*[constants.py, line 9 at r2](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTbxPjg8JSvnTPKP0Zo:-MUVw4cG1T7hXhYtr3on:b5bosel) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/098550121134edda43f0c73faa78ccd78aeffb98/constants.py#L9)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I think a couple of them are still "converts" instead of "convert" or "returns" instead of "return"?
</blockquote></details>

Done. I have gone over all the comments in the repo, and they all should be imperative now. 
___
*[csv_extractor.py, line 126 at r4](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTxbbP7DjAizJe6U0bX:-MUVwHAi9bPL6sp_VT0b:br9h3mb) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/fd2e52e1906ca8e2138db3053b6ac312412843f2/csv_extractor.py#L126)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

You can get the index without doing it manually by using `enumerate` - at least I think you can for a reader lol
```Python
for read_idx, line in enumerate(reader):
```
</blockquote></details>

I think this is simpler in terms of readability. 
___
*[engine_XML.py, line 88 at r4](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTxcvMs4ljMKsg0SXi7:-MUVwN795Nsas6AkeP81:b-896fix) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/fd2e52e1906ca8e2138db3053b6ac312412843f2/engine_XML.py#L88)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Nitpick but I think you could just factor out the `*1000` and not multiply it til the end?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-28 18:38 UTC, jacobdeery reviewed
All my comments are addressed. I'll let Wendi take one last look at it, but <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MUdvfih45OxB866e1LS:b-59ldb8)* status: 6 of 43 files reviewed, 3 unresolved discussions (waiting on @jacobdeery, @shillcoat, @usephysics, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2021-03-01 06:01 UTC, wendi-yu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MUgNAwvCDzUlwdP2smx:bg7igkv)* status: 6 of 43 files reviewed, 1 unresolved discussion (waiting on @jacobdeery, @shillcoat, and @usephysics)

___
*[csv_extractor.py, line 126 at r4](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-MTxbbP7DjAizJe6U0bX:-MUgMxNXBQks-dhJ9QMq:b9uar7x) ([raw file](https://github.com/waterloo-rocketry/rse-calculator/blob/fd2e52e1906ca8e2138db3053b6ac312412843f2/csv_extractor.py#L126)):*
<details><summary><i>Previously, Code-Titan wrote…</i></summary><blockquote>

I think this is simpler in terms of readability. 
</blockquote></details>

imo it's more reliable to use built in stuff (in case you forget to increment your own `idx`, for example) but up to you yeah


<!-- Sent from Reviewable.io -->

2021-03-02 01:30 UTC, shillcoat approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/rse-calculator/2#-:-MUkYgzAAh6H16MqWvYz:bnfp4nl)* status: 6 of 43 files reviewed, all discussions resolved (waiting on @jacobdeery and @usephysics)



<!-- Sent from Reviewable.io -->

2021-03-03 02:28 UTC, merged